-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 22:57:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `telefone_aluno` VARCHAR(45) NOT NULL,
  `email_aluno` VARCHAR(45) NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_Aluno_turma1_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id_func` INT NOT NULL AUTO_INCREMENT,
  `nome_func` VARCHAR(45) NOT NULL,
  `telefone_func` VARCHAR(45) NOT NULL,
  `email_func` VARCHAR(45) NOT NULL,
  `id_tipofunc` INT NOT NULL,
  PRIMARY KEY (`id_func`),
  INDEX `fk_Funcionario_tipo_func1_idx` (`id_tipofunc` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_tipo_func1`
    FOREIGN KEY (`id_tipofunc`)
    REFERENCES `mydb`.`Tipo_func` (`id_tipofunc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_func`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_func` (
  `id_tipofunc` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipofunc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome_turma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atraso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atraso` (
  `id_atraso` INT NOT NULL AUTO_INCREMENT,
  `data_atraso` DATE NOT NULL,
  `hora_atraso` TIME NOT NULL,
  `justificativa` VARCHAR(100) NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_atraso`),
  INDEX `fk_atraso_Aluno1_idx` (`id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_atraso_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`Aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_funcionario` (
  `id_turma` INT NOT NULL,
  `id_func` INT NOT NULL,
  `horario_aula` TIME NOT NULL,
  `nome_aula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_turma`, `id_func`),
  INDEX `fk_turma_has_Funcionario_Funcionario1_idx` (`id_func` ASC) VISIBLE,
  INDEX `fk_turma_has_Funcionario_turma1_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_turma_has_Funcionario_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_Funcionario_Funcionario1`
    FOREIGN KEY (`id_func`)
    REFERENCES `mydb`.`Funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
