-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 04:52:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `telefone_aluno` VARCHAR(45) NOT NULL,
  `email_aluno` VARCHAR(45) NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_Aluno_turma1_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id_func` INT NOT NULL AUTO_INCREMENT,
  `nome_func` VARCHAR(45) NOT NULL,
  `telefone_func` VARCHAR(45) NOT NULL,
  `email_func` VARCHAR(45) NOT NULL,
  `id_tipofunc` INT NOT NULL,
  PRIMARY KEY (`id_func`),
  INDEX `fk_Funcionario_tipo_func1_idx` (`id_tipofunc` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_tipo_func1`
    FOREIGN KEY (`id_tipofunc`)
    REFERENCES `mydb`.`Tipo_func` (`id_tipofunc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_func`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_func` (
  `id_tipofunc` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipofunc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome_turma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atraso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atraso` (
  `id_atraso` INT NOT NULL AUTO_INCREMENT,
  `data_atraso` DATE NOT NULL,
  `hora_atraso` TIME NOT NULL,
  `justificativa` VARCHAR(100) NOT NULL,
  `id_aluno` INT NOT NULL,
  `id_func` INT NOT NULL,
  PRIMARY KEY (`id_atraso`),
  INDEX `fk_atraso_Aluno1_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_atraso_Funcionario1_idx` (`id_func` ASC) VISIBLE,
  CONSTRAINT `fk_atraso_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`Aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atraso_Funcionario1`
    FOREIGN KEY (`id_func`)
    REFERENCES `mydb`.`Funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_funcionario` (
  `id_turma` INT NOT NULL,
  `id_func` INT NOT NULL,
  `horario_aula` TIME NOT NULL,
  `nome_aula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_turma`, `id_func`),
  INDEX `fk_turma_has_Funcionario_Funcionario1_idx` (`id_func` ASC) VISIBLE,
  INDEX `fk_turma_has_Funcionario_turma1_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_turma_has_Funcionario_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_Funcionario_Funcionario1`
    FOREIGN KEY (`id_func`)
    REFERENCES `mydb`.`Funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Inserir dados na tabela tipo_func
INSERT INTO `mydb`.`tipo_func`
(`tipo`)
VALUES
('Professor'),
('Funcionario');

-- Inserir dados na tabela turma
INSERT INTO `mydb`.`turma`
(`nome_turma`)
VALUES
('Turma A'),
('Turma B'),
('Turma C'),
('Turma D'),
('Turma E'),
('Turma F'),
('Turma G'),
('Turma H'),
('Turma I'),
('Turma J');

-- Inserir dados na tabela funcionario
INSERT INTO `mydb`.`funcionario`
(`nome_func`, `telefone_func`, `email_func`, `id_tipofunc`)
VALUES
('Carlos Almeida', '555-3333', 'carlos.almeida@example.com', 1),
('Fernanda Ramos', '555-4444', 'fernanda.ramos@example.com', 2),
('Paulo Fernandes', '555-5555', 'paulo.fernandes@example.com', 1),
('Tatiana Castro', '555-6666', 'tatiana.castro@example.com', 2),
('Rafael Martins', '555-7777', 'rafael.martins@example.com', 1),
('Clara Dias', '555-8888', 'clara.dias@example.com', 2),
('Rodrigo Silva', '555-9999', 'rodrigo.silva@example.com', 1),
('Mariana Costa', '555-1111', 'mariana.costa@example.com', 2),
('Lucas Ferreira', '555-2222', 'lucas.ferreira@example.com', 1),
('Beatriz Alves', '555-3333', 'beatriz.alves@example.com', 2);

-- Inserir dados na tabela aluno
INSERT INTO `mydb`.`aluno`
(`nome_aluno`, `telefone_aluno`, `email_aluno`, `id_turma`)
VALUES
('João Silva', '555-1234', 'joao.silva@example.com', 1),
('Maria Souza', '555-5678', 'maria.souza@example.com', 2),
('Pedro Oliveira', '555-8765', 'pedro.oliveira@example.com', 3),
('Ana Lima', '555-4321', 'ana.lima@example.com', 1),
('Lucas Mendes', '555-0987', 'lucas.mendes@example.com', 2),
('Julia Costa', '555-2222', 'julia.costa@example.com', 3),
('Bruno Rocha', '555-1111', 'bruno.rocha@example.com', 4),
('Fernanda Melo', '555-3333', 'fernanda.melo@example.com', 5),
('Renato Cardoso', '555-4444', 'renato.cardoso@example.com', 6),
('Alice Borges', '555-5555', 'alice.borges@example.com', 7);

-- Inserir dados na tabela turma_funcionario
INSERT INTO `mydb`.`turma_funcionario`
(`id_turma`, `id_func`, `horario_aula`, `nome_aula`)
VALUES
(1, 1, '08:00:00', 'Matemática'),
(2, 2, '09:00:00', 'História'),
(3, 3, '10:00:00', 'Ciências'),
(1, 3, '11:00:00', 'Inglês'),
(2, 4, '13:00:00', 'Educação Física'),
(3, 5, '14:00:00', 'Geografia'),
(4, 6, '08:00:00', 'Física'),
(5, 7, '09:00:00', 'Química'),
(6, 8, '10:00:00', 'Biologia'),
(7, 9, '11:00:00', 'Filosofia');

-- Inserir dados na tabela atraso, agora com id_func como chave estrangeira
INSERT INTO `mydb`.`atraso`
(`data_atraso`, `hora_atraso`, `justificativa`, `id_aluno`, `id_func`)
VALUES
('2023-09-10', '08:30:00', 'Trânsito', 1, 1),
('2023-09-11', '09:00:00', 'Consulta médica', 2, 2),
('2023-09-12', '08:45:00', 'Pneu furado', 3, 3),
('2023-09-13', '09:15:00', 'Problema familiar', 4, 4),
('2023-09-14', '08:50:00', 'Chuva forte', 5, 5),
('2023-09-15', '09:10:00', 'Engarrafamento', 6, 6),
('2023-09-16', '08:40:00', 'Problema no transporte público', 7, 7),
('2023-09-17', '09:05:00', 'Esquecimento do horário', 8, 8),
('2023-09-18', '08:55:00', 'Problema de saúde', 9, 9),
('2023-09-19', '09:20:00', 'Visita inesperada', 10, 10);